version = 1

[merge]
require_automerge_label = false
blocking_labels = ["blocked"]
method = "squash"
delete_branch_on_merge = true
prioritize_ready_to_merge = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["renovate"]

[merge.message]
title = "pull_request_title"
body = "github_default"
include_pr_number = true
body_type = "markdown"
strip_html_comments = true
include_coauthors = true

[approve]
auto_approve_usernames = ["renovate"]
auto_approve_labels = ["dependencies"]
