name = "kana"
main = "./dist/index.js"
compatibility_date = "2023-11-08"

node_compat = true
workers_dev = true

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[vars]
CLIENT_NAME = "Kana"
CLIENT_VERSION = "1.0.0"
