name = "kana"
main = "./dist/index.js"
compatibility_date = "2023-03-14"
compatibility_flags = [ "nodejs_compat" ]

node_compat = true
workers_dev = true

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = [ "**/*.js" ]

[vars]
CLIENT_NAME = "Kana"
